version: "3.8"
services:
  agent:
    build: agent-extended
    ports:
      - "8000:8000"
    environment:
      - OPENID_URL=http://keycloak:8080/realms/browser-copilot
      - MANIFEST_OPENID_URL=http://localhost:8080/realms/browser-copilot
    volumes:
      - ./agent-extended/gpt_agent:/usr/src/app/gpt_agent
  keycloak:
    image: quay.io/keycloak/keycloak
    ports: 
     - "8080:8080"
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
