name: Build
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: jetpack-io/devbox-install-action@v0.7.0
        with:
          enable-cache: 'true'
      - name: Install dependencies
        run: devbox run install
      - name: Build
        run: devbox run build
